spring:
  mail:
    protocol: smtp                   # 邮件协议
    host: smtp.163.com               # smtp 服务器地址 （163邮箱为例）
    port: 25                         # 端口号（163邮箱为例）
    username: ${USER_NAME}           # 发送人邮箱地址
    password: ${PASS_WORD}           # 授权码
    default-encoding: utf-8          # 编码字符集
    debug: true                      # 开启debug模式用户会完整打印邮件发送过程的日志

  datasource:
    url: jdbc:postgresql://rm-cn-g4t49zdur00074go.rwlb.rds.aliyuncs.com:5432/interview
    username: my_user
    password: zRT3LJNYGz@
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-init-sql: "CREATE EXTENSION IF NOT EXISTS vector;"
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        initializeSchema: true
        dimensions: 1536
        schemaName: public
        tableName: vector_store
        batching-strategy: TOKEN_COUNT # Optional: Controls how documents are batched for embedding
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch